# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  config.vm.provision :shell, :path => "vagrant-provision.sh"

end
